#!/bin/bash

#Переменная имени компьютера
name=$(hostname)

#Проверка является ли он Client
if [[ "$name" == "Client"  &&   -d /mnt/share_client ]]; then

#Создаем переменную и архив по имени день-месяц-год-час-мин-сек
  date=`date '+%d-%m-%Y-%H-%M-%S'`
  sudo tar czf "$date.tar.gz" /root/. /home/*/.*
  sudo chmod 755 "$date.tar.gz"
  
#Перемещение архива в директорию NFS
  sudo mv "$date.tar.gz" /mnt/share_client
  
#Задача для крон
  cd /tmp
  sudo touch crontab-arch
  sudo echo "05 8 * * * /tmp/backup.sh" | tee -a  /tmp/crontab-arch
  sudo crontab crontab-arch

else
  echo “Невозможно выполнить.Скрипт не для этого устройства”
fi
