#!/bin/bash


if [ $hostname="server” ]; then
  sudo apt-get nfs-kernel-server nfs-common portmap -y
  sudo mkdir /home/nfs
  sudo chown nobody:nogroup /home/nfs
  sudo nano /etc/exports
 
#share
  sudo exportfs -a
  sudo systemctl enable nfs-server
  sudo rount -t nfs 192.168.100.56:/home/nfs /mnt/nfs

  echo "server located"

elif [ $hostname="client" ]; then 
  sudo apt-get install nfs-common 
  
  echo "client located"

else
echo "Faild to find hostname"

fi
