#!/bin/bash

if [ $HOSTNAME == "Debian" ]; then

sudo apt-get install nfs-kernel-server nfs-common postmap -y
/etc/init.d/nfs-kernel-server start
/etc/init.d/portmap start

chkconfig --level 35 portmap on
chkconfig --level 35 nfs on
mkdir /nfsshare
vi /etc/exports
/nfsshare 192.168.5.39(rw,sync,no_root_squash)


else

showmount -e 192.168.5.37
Export list for 192.168.5.37:
/nfsshare 192.168.5.39
mount -t nfs 192.168.5.37:/nfsshare /mnt/nfsshare
vi /etc/fstab
192.168.5.37:/nfsshare on /mnt type nfs (rw,addr=192.168.5.39)

fi
